# Generated by Django 5.2.5 on 2025-08-25 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo de Préstamo')),
                ('tasa_interes_predeterminada', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de Interés Anual Predeterminada (%)')),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto Mínimo')),
                ('monto_maximo', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto Máximo')),
                ('plazo_maximo_meses', models.IntegerField(verbose_name='Plazo Máximo en Meses')),
                ('metodo_calculo', models.CharField(choices=[('frances', 'Francés (cuota fija)')], default='frances', max_length=20, verbose_name='Método de Cálculo')),
                ('comision_por_desembolso', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Comisión por Desembolso (%)')),
            ],
            options={
                'verbose_name': 'Tipo de Préstamo',
                'verbose_name_plural': 'Tipos de Préstamos',
                'db_table': 'prestamos_tipo_prestamo',
            },
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tipo_prestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_prestamos.tipoprestamo', verbose_name='Tipo de Préstamo'),
        ),
    ]
