# Generated by Django 5.1 on 2025-08-25 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0004_tipoprestamo_periodo_tasa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, help_text='Monto con el que la empresa inició operaciones. Solo debe existir un registro.', max_digits=15, verbose_name='Capital Inicial')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Capital de la Empresa',
                'verbose_name_plural': 'Capital de la Empresa',
                'db_table': 'prestamos_capital',
            },
        ),
    ]
