# Generated by Django 5.1 on 2025-08-26 14:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0005_capital'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='fecha_ultima_penalidad_calculada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Última Penalidad Calculada'),
        ),
        migrations.AddField(
            model_name='cuota',
            name='monto_penalidad_acumulada',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Penalidad Acumulada'),
        ),
        migrations.AddField(
            model_name='tipoprestamo',
            name='aplica_penalidad_sobre',
            field=models.CharField(choices=[('monto_cuota', 'Monto de la Cuota'), ('capital_pendiente', 'Capital Pendiente de la Cuota')], default='monto_cuota', help_text='Define sobre qué monto se calcula la penalidad diaria.', max_length=20, verbose_name='Aplica Penalidad Sobre'),
        ),
        migrations.AddField(
            model_name='tipoprestamo',
            name='dias_gracia',
            field=models.IntegerField(default=0, help_text='Número de días después del vencimiento antes de aplicar penalidad.', verbose_name='Días de Gracia'),
        ),
        migrations.AddField(
            model_name='tipoprestamo',
            name='tasa_penalidad_diaria',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Tasa diaria aplicada sobre el monto de la cuota vencida (ej. 0.01 para 1%).', max_digits=5, verbose_name='Tasa de Penalidad Diaria (%)'),
        ),
    ]
