# Generated by Django 5.1 on 2025-08-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0007_seed_loan_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Pago'),
        ),
    ]
