# Generated by Django 5.1 on 2025-08-29 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0008_alter_pago_fecha_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del Tipo de Gasto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Tipo de Gasto',
                'verbose_name_plural': 'Tipos de Gastos',
                'db_table': 'prestamos_tipo_gasto',
            },
        ),
        migrations.CreateModel(
            name='GastoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del Gasto')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripción Adicional')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos_asociados', to='gestion_prestamos.prestamo')),
                ('tipo_gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestion_prestamos.tipogasto', verbose_name='Tipo de Gasto')),
            ],
            options={
                'verbose_name': 'Gasto del Préstamo',
                'verbose_name_plural': 'Gastos del Préstamo',
                'db_table': 'prestamos_gasto_prestamo',
            },
        ),
    ]
