# Generated by Django 5.1 on 2025-08-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0011_cliente_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='debe_cambiar_contrasena',
            field=models.BooleanField(default=True),
        ),
    ]
