# Generated by Django 5.2.5 on 2025-08-30 18:00

from django.db import migrations

def create_user_groups(apps, schema_editor):
    """
    Crea los grupos de usuarios iniciales (Administradores y Clientes)
    y asigna los permisos correspondientes.
    """
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    # --- Crear Grupo de Administradores ---
    admin_group, created = Group.objects.get_or_create(name='Administradores')
    if created:
        # Asignar todos los permisos sobre los modelos de nuestras apps
        app_labels = ['gestion_prestamos', 'dashboard']
        content_types = ContentType.objects.filter(app_label__in=app_labels)
        permissions = Permission.objects.filter(content_type__in=content_types)
        admin_group.permissions.set(permissions)

    # --- Crear Grupo de Clientes ---
    # Este grupo no tendrá permisos por defecto, el acceso se controla en las vistas.
    client_group, created = Group.objects.get_or_create(name='Clientes')

class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0012_cliente_debe_cambiar_contrasena'),
    ]

    operations = [
        migrations.RunPython(create_user_groups),
    ]