# Generated by Django 5.2.5 on 2025-09-09 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0013_create_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('garantia', 'Garantía Monetaria'), ('documento', 'Documento/Requisito')], default='documento', max_length=10, verbose_name='Tipo de Requisito')),
                ('descripcion', models.CharField(help_text='Descripción del requisito (ej: Matrícula universitaria, Título de propiedad, etc.)', max_length=255)),
                ('valor_estimado', models.DecimalField(blank=True, decimal_places=2, help_text='Valor estimado (solo si aplica, para garantías monetarias)', max_digits=12, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='gestion_prestamos.prestamo')),
            ],
            options={
                'verbose_name': 'Requisito',
                'verbose_name_plural': 'Requisitos',
            },
        ),
    ]
