# Generated by Django 5.2.5 on 2025-09-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0017_prestamo_fecha_inicio_pago_prestamo_tasa_mora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='periodo_tasa',
            field=models.CharField(choices=[('anual', 'Anual'), ('mensual', 'Mensual')], default='anual', max_length=10, verbose_name='Periodo de la Tasa'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=2, help_text='En porcentaje (%)', max_digits=5, verbose_name='Tasa de Interés'),
        ),
    ]
