# Generated by Django 5.1 on 2025-09-10 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0018_prestamo_periodo_tasa_alter_prestamo_tasa_interes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200, verbose_name='Nombre Completo')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula')),
                ('lugar_trabajo', models.CharField(max_length=200, verbose_name='Lugar de Trabajo')),
                ('ingresos_mensuales', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ingresos Mensuales')),
            ],
            options={
                'verbose_name': 'Garante',
                'verbose_name_plural': 'Garantes',
                'db_table': 'prestamos_garante',
            },
        ),
        migrations.AddField(
            model_name='prestamo',
            name='garante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_prestamos.garante', verbose_name='Garante'),
        ),
    ]
