# Generated by Django 5.1 on 2025-09-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0022_improve_requisito_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='manejo_gastos',
            field=models.CharField(choices=[('sumar_al_capital', 'Sumar al Capital'), ('restar_del_desembolso', 'Restar del Desembolso')], default='sumar_al_capital', max_length=30, verbose_name='Manejo de Gastos Adicionales'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='monto_desembolsado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto Desembolsado'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='total_gastos_asociados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total de Gastos Asociados'),
        ),
    ]
