# Generated by Django 5.2.5 on 2025-08-21 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='Cédula o Identificación')),
                ('direccion', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField(verbose_name='Número de Cuota')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha de Vencimiento')),
                ('monto_cuota', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto de la Cuota')),
                ('capital', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Capital')),
                ('interes', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Interés')),
                ('saldo_pendiente', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Pendiente')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida')], default='pendiente', max_length=10, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['prestamo', 'numero_cuota'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_pagado', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto Pagado')),
                ('fecha_pago', models.DateField(verbose_name='Fecha de Pago')),
                ('cuota', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pago', to='prestamos.cuota')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Monto del Préstamo')),
                ('tasa_interes', models.DecimalField(decimal_places=2, help_text='En porcentaje (%)', max_digits=5, verbose_name='Tasa de Interés Anual')),
                ('plazo', models.IntegerField(help_text='En meses', verbose_name='Plazo')),
                ('fecha_desembolso', models.DateField(verbose_name='Fecha de Desembolso')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='activo', max_length=10, verbose_name='Estado')),
                ('frecuencia_pago', models.CharField(choices=[('mensual', 'Mensual'), ('quincenal', 'Quincenal')], default='mensual', max_length=10, verbose_name='Frecuencia de Pago')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='prestamos.cliente')),
            ],
            options={
                'verbose_name': 'Préstamo',
                'verbose_name_plural': 'Préstamos',
            },
        ),
        migrations.AddField(
            model_name='cuota',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='prestamos.prestamo'),
        ),
        migrations.AlterUniqueTogether(
            name='cuota',
            unique_together={('prestamo', 'numero_cuota')},
        ),
    ]
