# Generated by Django 5.1 on 2025-08-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0002_tipoprestamo_prestamo_tipo_prestamo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoprestamo',
            name='plazo_minimo_meses',
            field=models.IntegerField(default=1, verbose_name='Plazo Mínimo en Meses'),
        ),
    ]
