# Generated by Django 5.1 on 2025-08-25 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0003_tipoprestamo_plazo_minimo_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoprestamo',
            name='periodo_tasa',
            field=models.CharField(choices=[('anual', 'Anual'), ('mensual', 'Mensual')], default='anual', max_length=10, verbose_name='Periodo de la Tasa'),
        ),
        migrations.AlterField(
            model_name='tipoprestamo',
            name='tasa_interes_predeterminada',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tasa de Interés Predeterminada (%)'),
        ),
    ]
