# Generated by Django 5.0.7 on 2024-07-25 15:24

from django.db import migrations
from decimal import Decimal

def create_loan_types(apps, schema_editor):
    """
    Crea los tipos de préstamo iniciales en la base de datos.
    """
    TipoPrestamo = apps.get_model('gestion_prestamos', 'TipoPrestamo')
    
    loan_types = [
        {
            "nombre": "Personal",
            "tasa_interes_predeterminada": Decimal('22.0'),
            "periodo_tasa": "anual",
            "monto_minimo": Decimal('500.00'),
            "monto_maximo": Decimal('25000.00'),
            "plazo_minimo_meses": 6,
            "plazo_maximo_meses": 48,
            "tasa_penalidad_diaria": Decimal('0.001'), # 0.1%
            "dias_gracia": 5,
            "aplica_penalidad_sobre": "monto_cuota",
            "metodo_calculo": "frances",
            "comision_por_desembolso": Decimal('1.0')
        },
        {
            "nombre": "Vehículo",
            "tasa_interes_predeterminada": Decimal('12.5'),
            "periodo_tasa": "anual",
            "monto_minimo": Decimal('5000.00'),
            "monto_maximo": Decimal('50000.00'),
            "plazo_minimo_meses": 12,
            "plazo_maximo_meses": 72,
            "tasa_penalidad_diaria": Decimal('0.0005'), # 0.05%
            "dias_gracia": 5,
            "aplica_penalidad_sobre": "monto_cuota",
            "metodo_calculo": "frances",
            "comision_por_desembolso": Decimal('0.5')
        },
        {
            "nombre": "Adelanto de Nómina",
            "tasa_interes_predeterminada": Decimal('35.0'),
            "periodo_tasa": "anual",
            "monto_minimo": Decimal('100.00'),
            "monto_maximo": Decimal('2000.00'),
            "plazo_minimo_meses": 1,
            "plazo_maximo_meses": 3,
            "tasa_penalidad_diaria": Decimal('0.002'), # 0.2%
            "dias_gracia": 2,
            "aplica_penalidad_sobre": "monto_cuota",
            "metodo_calculo": "frances",
            "comision_por_desembolso": Decimal('2.0')
        },
        {
            "nombre": "Pequeña Empresa",
            "tasa_interes_predeterminada": Decimal('18.0'),
            "periodo_tasa": "anual",
            "monto_minimo": Decimal('2000.00'),
            "monto_maximo": Decimal('100000.00'),
            "plazo_minimo_meses": 12,
            "plazo_maximo_meses": 60,
            "tasa_penalidad_diaria": Decimal('0.0008'), # 0.08%
            "dias_gracia": 7,
            "aplica_penalidad_sobre": "monto_cuota",
            "metodo_calculo": "frances",
            "comision_por_desembolso": Decimal('1.5')
        }
    ]

    for loan_data in loan_types:
        TipoPrestamo.objects.create(**loan_data)

def delete_loan_types(apps, schema_editor):
    """
    Elimina los tipos de préstamo creados si se revierte la migración.
    """
    TipoPrestamo = apps.get_model('gestion_prestamos', 'TipoPrestamo')
    loan_names = ["Personal", "Vehículo", "Adelanto de Nómina", "Pequeña Empresa"]
    TipoPrestamo.objects.filter(nombre__in=loan_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0006_cuota_fecha_ultima_penalidad_calculada_and_more'),
    ]

    operations = [
        migrations.RunPython(create_loan_types, reverse_code=delete_loan_types),
    ]