# Generated by Django 5.2.5 on 2025-09-09 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0013_create_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Descripción de la garantía (ej: Vehículo Toyota Camry 2015, Hipoteca de la propiedad en...', max_length=255)),
                ('valor_estimado', models.DecimalField(decimal_places=2, help_text='Valor estimado de la garantía en el mercado', max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias', to='gestion_prestamos.prestamo')),
            ],
            options={
                'verbose_name': 'Garantía',
                'verbose_name_plural': 'Garantías',
            },
        ),
    ]
