# Generated by Django 5.2.5 on 2025-09-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0014_requisito'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoprestamo',
            name='requiere_garantia',
            field=models.BooleanField(default=False, help_text='Marcar si este tipo de préstamo exige una garantía o requisito adicional.', verbose_name='¿Requiere Garantía?'),
        ),
    ]
