# Generated by Django 5.2.5 on 2025-09-10 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0015_tipoprestamo_requiere_garantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='apodo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apodo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('soltero', 'Soltero/a'), ('casado', 'Casado/a'), ('divorciado', 'Divorciado/a'), ('viudo', 'Viudo/a')], max_length=20, null=True, verbose_name='Estado Civil'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sexo',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('femenino', 'Femenino')], max_length=20, null=True, verbose_name='Sexo'),
        ),
    ]
