# Generated by Django 5.2.5 on 2025-09-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0016_cliente_apodo_cliente_estado_civil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_inicio_pago',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Inicio de Pago'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tasa_mora',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='En porcentaje (%)', max_digits=5, null=True, verbose_name='Tasa de Mora Anual'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tipo_amortizacion',
            field=models.CharField(choices=[('saldo_insoluto', 'Saldo Insoluto'), ('capital_fijo', 'Capital Fijo'), ('interes_simple', 'Interés Simple')], default='saldo_insoluto', max_length=20, verbose_name='Tipo de Amortización'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='frecuencia_pago',
            field=models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], default='mensual', max_length=10, verbose_name='Frecuencia de Pago'),
        ),
    ]
