# Generated by Django 5.1 on 2025-09-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0019_garante_prestamo_garante'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cargo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo o Posición'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ingresos_mensuales',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ingresos Mensuales'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre_empresa',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la Empresa'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_trabajo',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono del Trabajo'),
        ),
    ]
