# Generated by Django 5.1 on 2025-09-10 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0020_cliente_cargo_cliente_ingresos_mensuales_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fecha_ingreso_trabajo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Ingreso al Trabajo'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='trabajo_actual',
            field=models.BooleanField(default=True, verbose_name='¿Es su trabajo actual?'),
        ),
    ]
