# Generated by Django 5.1 on 2025-09-11 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0021_cliente_fecha_ingreso_trabajo_cliente_trabajo_actual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requisito',
            name='descripcion',
            field=models.CharField(help_text='Detalles del requisito (ej: Marca y placa del vehículo, No. de matrícula del inmueble, etc.)', max_length=255),
        ),
        migrations.AlterField(
            model_name='requisito',
            name='tipo',
            field=models.CharField(choices=[('titulo_vehiculo', 'Título de Vehículo'), ('titulo_propiedad', 'Título de Propiedad'), ('garantia_solidaria', 'Garantía Solidaria'), ('carta_trabajo', 'Carta de Trabajo'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de Requisito'),
        ),
    ]
