# Generated by Django 5.1 on 2025-09-12 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0023_add_expense_handling_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prestamo',
            name='tasa_mora',
        ),
    ]
