# Generated by Django 5.1 on 2025-09-29 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0024_remove_prestamo_tasa_mora'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='prestamo',
            name='unique_active_loan_per_client',
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', max_length=10, verbose_name='Estado'),
        ),
        migrations.AddConstraint(
            model_name='prestamo',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'aprobado')), fields=('cliente',), name='unique_active_loan_per_client'),
        ),
    ]
