# Generated by Django 5.1 on 2025-09-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_prestamos', '0025_remove_prestamo_unique_active_loan_per_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Aprobación'),
        ),
    ]
